---
- name: update launch config
  ec2_lc:
    name:                    "{{env}}-{{stack}}-{{layer}}-{{ new_ami_id }}"
    image_id:                "{{ new_ami_id }}"
    key_name:                "{{ aws_key_name }}"
    security_groups:         [ "{{ hostvars[inventory_hostname][env + '_application'] }}" ]
    region:                  "{{ aws_region }}"
    instance_type:           "{{ asg_default_instance_type }}"
    assign_public_ip:        "{{ asg_assign_public_ip }}"
    user_data:               "{{ lookup('template', './user_data.sh.j2') }}"
    instance_profile_name:   "{{ env }}_web"

- name: describe-auto-scaling-groups
  shell: >
    aws autoscaling describe-auto-scaling-groups --region {{ aws_region }} --auto-scaling-group-names {{ env }}-{{ stack }}-{{ layer }}
  register: describe_auto_scaling_groups_output

- name: set describe_auto_scaling_groups_output_json
  set_fact:
    describe_auto_scaling_groups_output_json: "{{describe_auto_scaling_groups_output.stdout | from_json }}"

# The conditional at the end of this task ensures that the autoscaling group is created only if it does not exist
- name: create autoscaling group
  ec2_asg:
    name:                    "{{ env }}-{{ stack }}-{{ layer }}"
    load_balancers:          [ "{{ web_elb }}"]
    launch_config_name:      "{{ env }}-{{ stack }}-{{ layer }}-{{ new_ami_id }}"
    health_check_period:     "{{ asg_health_check_period }}"
    health_check_type:       "{{ asg_health_check_type }}"
    replace_all_instances:   "{{ asg_replace_all_instances }}"
    replace_batch_size:      "{{ asg_replace_batch_size }}"
    min_size:                "{{ asg_min_size }}"
    max_size:                "{{ asg_max_size }}"
    desired_capacity:        "{{ asg_desired_capacity }}"
    region:                  "{{ aws_region }}"
    vpc_zone_identifier:     "{{ asg_vpc_zone_identifier | default([private_working_az1]) }}"
    availability_zones:      "{{ asg_availability_zones }}"
    wait_for_instances:      "{{ asg_wait_for_instances }}"
    default_cooldown:        "{{ asg_default_cooldown }}"
    tags:
      - Env:   "{{ env }}"
      - Stack: "{{ stack }}"
      - Layer: "{{ layer }}"
      - Name:  "{{ env }}-{{ stack }}-{{ layer }}"
  when: (describe_auto_scaling_groups_output_json.AutoScalingGroups[0] is defined) and (describe_auto_scaling_groups_output_json.AutoScalingGroups[0].AutoScalingGroupName != {{ env }}-{{ stack }}-{{ layer }})

- name: update autoscaling group via aws cli
  shell: >
    aws autoscaling update-auto-scaling-group
    --region                    "{{ aws_region }}"
    --auto-scaling-group-name   "{{ env }}-{{ stack }}-{{ layer }}"
    --launch-configuration-name "{{ env }}-{{ stack }}-{{ layer }}-{{ new_ami_id }}"
    --min-size                  "{{ asg_min_size }}"
    --max-size                  "{{ asg_max_size }}"
    --desired-capacity          "{{ asg_desired_capacity }}"
    --default-cooldown          "{{ asg_default_cooldown }}"
    --availability-zones         {{ asg_availability_zones| join(" ") }}
    --health-check-type         "{{ asg_health_check_type }}"
    --health-check-grace-period "{{ asg_health_check_period }}"
    --vpc-zone-identifier        {{ asg_vpc_zone_identifier | join(",") }}
